### ISSUE TITLE
Convert table to js object/array?

### ISSUE THREAD

**Issue by fuzzthink** [kripken/lua.vm.js#22]
Any idea how to pass/convert a 1dimensional table to a js array or table to js object?

**Comment by fuzzthink** [comment]
A hack that worked to create js function that pushes values to a global array and on lua side, call that js function for each item in the table.  Any better method?

**Comment by daurnimator** [comment]
Lua tables and JS arrays have very different semantics.
A cheap way to shallow convert a table is to just use the Array constructor with unpack:

```lua
t = {1,2,3}
my_js_array = js.global:Array(table.unpack(t))
````

**Comment by KelsonBall** [comment]
Here is a lua function I put together that translates a table recursively to a javascript object. Doesn't support  metatables/prototypes. If a better solution has been found since this thread was last loved I'd love to hear about it!

	function gettranslator(jsglobal)
		local function translate(inTable)		
			-- Array or Object?
			local isArray = true		
			for k,v in pairs(inTable) do					
				if not tonumber(k) then
					isArray = false
					break
				end
			end		

			-- Recurse on table elements
			local output = {}		
			for k,v in pairs(inTable) do
				if type(v) == type({}) then
					output[k] = translate(v)
				else			
					output[k] = v
				end
			end

			-- Create new Array or Object
			if isArray then			
				return jsglobal:Array(table.unpack(output))
			else			
				local obj = jsglobal:Object()
				for k,v in pairs(output) do
					obj[k] = v
				end
				return obj
			end
		end

		-- Return translator func
		return translate
	end

	return gettranslator

**Comment by daurnimator** [comment]
> Here is a lua function I put together that translates a table recursively to a javascript object.

I do question if that's something people *want*.
It often seems like it at first glance, but if you look closer, you often want referential integrity as well as preserving cycles, table keys, metatables, garbage collection behaviour and more.

> -- Array or Object?
> 		local isArray = true		
> 		for k,v in pairs(inTable) do					
> 			if not tonumber(k) then
> 				isArray = false
> 				break
> 			end
> 		end

This is a very expensive way to check this. Instead, I suggest just looking at `inTable[1]`. Also don't forget that javascript arrays *can* have other properties set on them.

> type({})

Why? Use `"table"`

> output[k] = v

Don't forget to check if `k` is valid as a javascript key.

> return jsglobal:Array(table.unpack(output))

This will fail if there are more than ~8000 elements.
You'll need to fall back to an iterative approach.

> local obj = jsglobal:Object()
> 			for k,v in pairs(output) do
> 				obj[k] = v
> 			end
> 			return obj

So you assign into `output`, then assign into `obj`? Just do the assign *once* into the returned object.

**Comment by KelsonBall** [comment]
For my use case (_sending small object literals as parameters to a js library_) this is working great. If you are working with larger, more complex objects then parsing to and from json makes a lot more sense. Otherwise, this approach eliminates the need for writing _any_ js.

`type({})` avoids a magic string, misspelling table would be a much harder issue to find than misspelling '{}', as my approach is caught by the parser.

**Comment by daurnimator** [comment]
> type({}) avoids a magic string, misspelling table would be a much harder issue to find than misspelling '{}', as my approach is caught by the parser.

You might as well mis-spell `type` too. It's an equally 'magic' name.

**Comment by KelsonBall** [comment]
> is caught by the parser

**Comment by daurnimator** [comment]
> is caught by the parser

Spelling `typo` instead of `type` would *not* be caught by the parser.
