### ISSUE TITLE
"arg" doesn't work

### ISSUE THREAD

**Issue by blackmiaool** [kripken/lua.vm.js#29]
Variable number of arguments("..." and "arg") doesn't work.

**Comment by daurnimator** [comment]
What do you mean it doesn't work?

It works fine....
```js
> L.execute('return ...', 1, 2, 3)
[1, 2, 3]
```

In [repl](https://kripken.github.io/lua.vm.js/repl.html):
```lua
function foo(...)
   print("foo", ...)
end
foo("testing", "varargs")
```

**Comment by blackmiaool** [comment]
Thanks for replying . Exactly , the keyword "arg" doesn't work.

**Comment by daurnimator** [comment]
> Thanks for replying . Exactly , the keyword "arg" doesn't work.
`arg` is not a keyword in lua.

**Comment by daurnimator** [comment]
You may be reading material related to lua 5.0? `arg` was a magical local variable there.
That `arg` was removed with the release of lua 5.1.

lua.vm.js currently uses lua 5.2; to be upgraded to lua 5.3 when I get the time.

**Comment by blackmiaool** [comment]
So that's it...thx
