### ISSUE TITLE
io.open not working

### ISSUE THREAD

**Issue by gianpiero** [kripken/lua.vm.js#30]
I am trying to execute, from node, a simple chunk of lua code that has to open a file and print the content on the screen. Here how to reproduce it:

```
var LuaVM = require('lua.vm.js');
var L = new LuaVM.Lua.State();

var theCode = "local myFile, err = io.open('/tmp/file.txt') \
    if not myFile then print(err) return end \
    io.input(myFile) \
    local theContent = io.read('*all') \
    print(theContent)"

var result = L.execute(theCode)
console.log(result)
```

The output is:

```
/tmp/file.txt: No such file or directory
[]
```

I verified that the file /tmp/file.txt exists.

**Comment by daurnimator** [comment]
lua.vm.js virtualises IO into an in memory virtual file system (using emscripten)
This is because it's primarily targeted at the browser, where real IO doesn't exist.

If you're running in node, you can use the node file functions:
```lua
local file = js.global:require"fs":open("/tmp/file.txt")
```

**Comment by gianpiero** [comment]
Is there a way around? The example i posted was a simplified version of what I am trying to do. 
I was trying to call a Lua file that parses xml files and return a table. That lua file does the io.open

so is not that i want the content of the file in the browser but i want the lua code to return me a table after parsing some external file...

**Comment by daurnimator** [comment]
> Is there a way around?  The example i posted was a simplified version of what I am trying to do. 
I was trying to call a Lua file that parses xml files and return a table. That lua file does the io.open

hrm. make a file and then hand it over?

**Comment by gianpiero** [comment]
It sounds like a good idea. Thanks. 

But I am having trouble with `js.global`. Do I have to do something to init global?

I am doing 

```
function executeLua(L,code) {
  try {
    L.execute(code);
  } catch(e) {
    console.log(e.toString());
  }
}

function test2(){
  var LuaVM = require('lua.vm.js');
  var L = new LuaVM.Lua.State();
  var theCode =
  "print(type(js.global:eval('[0,1,2,3,4,5][3]')))"
  var result = executeLua(L,theCode)
}

test2()
```

I get an exception:
   
    Lua.Error: [string "?"]:1: attempt to call method 'eval' (a nil value)

same goes for `require`

What am I missing?

**Comment by daurnimator** [comment]
> But I am having trouble with js.global. Do I have to do something to init global?

Hrm, it looks like the way I pass the global environment in is broken in node (though it works in the browser).
Will have to look into this.

**Comment by gianpiero** [comment]
@daurnimator I am closing this issue, since the io problem is not a bug, and creating a new issue https://github.com/kripken/lua.vm.js/issues/31 related to the `js.gloabl`

Please let me know if I can help in speeding up the fix.
