### ISSUE TITLE
npm install lua.vm.js npm ERR! 404 Not Found

### ISSUE THREAD

**Issue by brendonco** [kripken/lua.vm.js#32]
Hi,

when I do an npm install lua.vm.js, I get a 404 Not found. I'm using mac.

**Comment by daurnimator** [comment]
lua.vm.js is not available via npm.

**Comment by brendonco** [comment]
how do I use it in web single page?

**Comment by brendonco** [comment]
and there is an instruction to use NPM from this site: https://github.com/kripken/lua.vm.js

**Comment by daurnimator** [comment]
> web single page

what do you mean?

You can just include it with a script tag: https://github.com/kripken/lua.vm.js/blob/gh-pages/script_example.html#L47

**Comment by daurnimator** [comment]
> and there is an instruction to use NPM from this site: https://github.com/kripken/lua.vm.js

oh... hmmm. I've never maintained that bit. @kripken, did you ever actually publish something to npm index?

**Comment by brendonco** [comment]
i'm using require.js to load the module, does it allow to do that?

**Comment by rom1504** [comment]
seems there is https://www.npmjs.com/package/luaworker

**Comment by rom1504** [comment]
I took the initiative of publishing it https://www.npmjs.com/package/lua.vm.js (I changed nothing, just did npm publish).
I added daurnimator as collaborator on npm (@kripken doesn't seem to have an account there ?)

**Comment by daurnimator** [comment]
Thanks. I thought someone else already had the 'lua.vm.js' name on github.
I have no idea the version as-is works; hopefully I'll get time to look into it next week.

**Comment by rom1504** [comment]
@daurnimator it does work, the example on the README works for example, and I'm using it to execute and get the data from some wiki scripts ( http://minecraft.gamepedia.com/Module:Inventory_slot/Aliases )  and it works fine :)

**Comment by daurnimator** [comment]
Fixed :)
