### ISSUE TITLE
js.global

### ISSUE THREAD

**Issue by brendonco** [kripken/lua.vm.js#33]
is there a way to bind back from lua table to js.global?

e.g.
```
function MyJSObject()
  local x = {"test1", "test2"}
  return js.global.existingjsObject = x
end
```

**Comment by daurnimator** [comment]
Yes.
What you have will work; however lua doesn't support statements as expressions.

Try:
```lua
function MyJSObject()
    local x = {"test1", "test2"}
    js.global.existingjsObject = x
    return x
end
```

**Comment by brendonco** [comment]
Thanks daurnimator.  It did work but the object in ```js.global.existingjsObject``` became a lua table.  If I want to remain the same js object before, is there a parser to do that?

**Comment by daurnimator** [comment]
>If I want to remain the same js object before

What do you mean "before"? You just created a new lua table and added it to the JavaScript global scope.

**Comment by brendonco** [comment]
it's ok I found a separate thread that convert lua to js array object

```
js.global:Array(table.unpack(x))
```

Thanks

**Comment by daurnimator** [comment]
You can also do it iteratively:
```lua
local myjsarray = js.new(js.global.Array)
for i=0, 99 do -- note starting from 0 instead of 1
   myjsarray[i] = math.random()
end
js.global.foo = myjsarray
```
