### ISSUE TITLE
callback when compile lua script is done

### ISSUE THREAD

**Issue by brendonco** [kripken/lua.vm.js#34]
Is there a callback after ```l.execute(code)``` is done? e.g. similar to Module.print?

**Comment by daurnimator** [comment]
> Is there a callback after l.execute(code) is done?
It's done as soon as it returns.

**Comment by brendonco** [comment]
how do I check ```l.execute(code)``` is done?

**Comment by daurnimator** [comment]
> how do I check l.execute(code) is done?

When it returns.

```js
L.execute("do_something_lua()")
// done now.
```
