### ISSUE TITLE
lua code not compiling after minified lua.vm.js

### ISSUE THREAD

**Issue by brendonco** [kripken/lua.vm.js#35]
Hi, after ```lua.vm.js``` is minified, lua script are not executing.  Have anyone tried minifying ```lua.vm.js``` and having code not compiling when ```L.execute(code)```?

**Comment by daurnimator** [comment]
> Hi, after lua.vm.js is minified, lua script are not executing. Have anyone tried minifying lua.vm.js and having code not compiling when L.execute(code)?

What minifier did you use?
If a minifier breaks code, it's a broken minifier...

**Comment by brendonco** [comment]
I see.  I used grunt-contrib-uglify
