### ISSUE TITLE
One argument not being passed. 

### ISSUE THREAD

**Issue by jaredallard** [kripken/lua.vm.js#39]
Observe:

script

```js
  inject_js(this.l, function() {
    console.log(arguments);
  }, "test_args")
```

inject_js

```js
function inject_js(state, code, global) {
  state.pushjs(code);
  state.setglobal(global);
  state.pop(0); // may or may not be needed.
}
```

lua

```lua
test_args("hello", "world")
```

output:

```js
{ '0': 'world' }
```

Hope that sums this up!

**Comment by daurnimator** [comment]
the first argument to a javascript function appears as `this`.
```
  inject_js(this.l, function() {
    console.log(this, arguments);
  }, "test_args")
```

**Comment by jaredallard** [comment]
Thank you! On another question, how would I convert a JS table to a Lua table?

**Comment by daurnimator** [comment]
> Thank you! On another question, how would I convert a JS array to a Lua table?

See https://github.com/kripken/lua.vm.js/issues/22
