### ISSUE TITLE
Script code not executed when using src attribute

### ISSUE THREAD

**Issue by MangelMaxime** [kripken/lua.vm.js#40]
Hi guys,

I am trying to use `lua.vm.js` in my web site.

If i add directly the code inside the script tags like so :

```html
<script src="/static/js/lua.vm.js"></script>
<script type="text/lua">
js.global:alert('hello from Lua script tag in HTML!') -- this is Lua!
</script>
```

It's fully working.

But if I try to add it using the `src` attribute, it's not executed

```html
<script src="/static/js/lua.vm.js"></script>
<script type="text/lua" src="/static/lua/app.lua"></script>
```

Here is my  `app.lua` file :

```lua
js.global:alert('hello from Lua script tag in HTML!') -- this is Lua!
```

**Comment by daurnimator** [comment]
Code in `src` attributes is not currently supported.
Sadly browsers make it impossible for us to get JS equivalent semantics here: CORS limitations will always make what we shim in inferior.
Perhaps we should add it anyway though?

**Comment by MangelMaxime** [comment]
This is a sad news.

The reason I would like to use `src` attributes is that I am using `Lapis framework` and writing script directly inside the file is very ugly.

See the `raw ...` line.

```moon
-- views/DefaultLayout.moon
import Widget from require "lapis.html"

class DefaultLayout extends Widget
    content: =>
        html_5 ->
            meta charset: "utf-8"
            head ->
                title @title or "Hybris Tracker",
                link rel: "stylesheet", type: "text/css", href: "/static/css/knacss.css",
                link rel: "stylesheet", type: "text/css", href: "/static/css/style.css"
            body class: "center w80", -> @content_for "inner"
            script src: "/static/js/lua.vm.js"
            raw "<script type=\"text/lua\">js.global:alert('hello from Lua script tag in HTML!') -- this is Lua!</script>"
            script type: "text/lua", src: "/static/lua/app.lua"
```

I saw in one of the example the REPL one that you execute lua code by explicitly calling it :

```html
<script>
/* ... */
function executeLua(code, clear) {
  if (clear) {
    outputElement.style.color = null;
    outputElement.textContent = '';
  }
  try {
    L.execute(code);
  } catch(e) {
    outputElement.style.color = "red";
    outputElement.textContent = e.toString();
  }
}
</script>
```

Do you think that it can be a `ugly` way (of course) to work around the problem for a temporary time.
Because, if the code is correctly written then we can attach the execution to event listener, or immediate execution depending of the call. (I hope i am clear enough).

What is your opinion ?

**Comment by MangelMaxime** [comment]
I have try to implement my previous proposition. Here is the code :

File `app_helper.js` :
```javascript
function executeLua(code) {
	try {
		L.execute(code);
	} catch(e) {
		console.error(e.toString());
	}
}

function loadApp() {
    var xmlhttp;

    if (window.XMLHttpRequest) {
        // code for IE7+, Firefox, Chrome, Opera, Safari
        xmlhttp = new XMLHttpRequest();
    } else {
        // code for IE6, IE5
        xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
    }

    xmlhttp.onreadystatechange = function() {
        if (xmlhttp.readyState == XMLHttpRequest.DONE ) {
           if(xmlhttp.status == 200){
               executeLua(xmlhttp.responseText);
           }
           else if(xmlhttp.status == 400) {
              alert('There was an error 400')
           }
           else {
               alert('something else other than 200 was returned')
           }
        }
    }

    xmlhttp.open("GET", "/static/lua/app.lua", true);
    xmlhttp.send();
}
```

File  `layout.html` :
```html
<!-- ... -->
<script>loadApp()</script>
<!-- ... -->
```

File `app.lua`:
```lua
js.global:alert('hello from Lua script tag in HTML!') -- this is Lua!
```

I got the expected result :

![image](https://cloud.githubusercontent.com/assets/4760796/11769804/3564caa4-a1f0-11e5-9b64-0e4432f4bad6.png)

Is there any limitation to this hack ? I am asking you because I just starting with `lua.vm.js`

**Comment by daurnimator** [comment]
> Is there any limitation to this hack ? 

IIRC, browsers will run a script tag with a `src` attribute as javascript, no matter what you specify for the `type`.

This is in addition to the fact that script tags can load javascript from anywhere; while an XHR is limited by browser policys.

**Comment by MangelMaxime** [comment]
Yes,  I saw that script tag with sec attributes as been loaded as Javascript. 

I will have to check the browsers policy rules to see the limitation of XHR. Otherwise I will try to add a new way to use fill the script for lapis using read file content on the server side that could be another solution to use external file to handle the Lua code on server side. 

Thanks for all your time 😊

**Comment by daurnimator** [comment]
> I will have to check the browsers policy rules to see the limitation of XHR. Otherwise I will try to add a new way to use fill the script for lapis using read file content on the server side that could be another solution to use external file to handle the Lua code on server side.

You could always just use `require` from lua. Insert into the page:
```html
<script type="text/lua">
require ".static.lua.app":start()
</script>
```

In lua.vm.js, `require` has a HTTP searcher

**Comment by MangelMaxime** [comment]
Oh, it's a more clear way to call it. We try it, thank you :)

**Comment by vadi2** [comment]
I've documented this as https://github.com/kripken/lua.vm.js/wiki/How-to-load-my-Lua-from--script-src=%22%22-%3F.

**Comment by MangelMaxime** [comment]
Just one more question, is `require` a sync or async method ?

**Comment by daurnimator** [comment]
> Just one more question, is require a sync or async method ?

Sync. To do otherwise would break with the standardised lua API.
You're free to write your own async function for loading code though.

**Comment by MangelMaxime** [comment]
Thanks for the answer. I am wanting it to be sync so it's all good :)
